version: '3.6'
services:
  front:
    image: nginx:alpine
    volumes:
      - $PWD/front.html:/usr/share/nginx/html/index.html

  back:
    image: nginx:alpine
    volumes:
      - $PWD/back.html:/usr/share/nginx/html/index.html

  proxy:
    depends_on:
      - front
      - back
    image: nginx:alpine
    volumes: 
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1122:8080